# Generated by Django 3.2.20 on 2023-12-14 22:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_order_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='deliver_day',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 15, 22, 6, 8, 456560)),
        ),
    ]
