# Generated by Django 3.2.20 on 2023-12-14 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_order_deliver_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='deliver_day',
            field=models.CharField(max_length=10),
        ),
    ]
