# Generated by Django 3.2.20 on 2023-12-14 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0007_alter_order_deliver_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='deliver_day',
            field=models.CharField(choices=[('1', 'Monday'), ('2', 'Tuesday'), ('3', 'Wednesday'), ('4', 'Thursday'), ('5', 'Friday'), ('6', 'Saturday'), ('7', 'Sunday')], max_length=10),
        ),
    ]
