# Generated by Django 3.2.20 on 2023-08-31 21:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0003_product_allergens"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="lifespan",
        ),
    ]
